eureka:
     instance:
        statusPageUrlPath: /actuator/info
        healthCheckUrlPath: /actuator/health
     client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
          defaultZone: http://${EUREKA_HOST:aliyun}:${EUREKA_PORT:8761}/eureka/