version: '2'
services:
  eureka:
    image: registry.cn-hangzhou.aliyuncs.com/mengstar/mb-center
    ports:
      - "8761:8761"
  config:
    image: registry.cn-hangzhou.aliyuncs.com/mengstar/mb-config
    ports:
      - "8888:8888"
    depends_on:
      - eureka
    environment:
      - EUREKA_HOST=eureka
      - EUREKA_PORT=8761

