spring:
    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: create
    datasource:
      url: jdbc:mysql://aliyun.com:3306/mbcps?characterEncoding=UTF-8
      username: root
      password: password
      driver-class-name: com.mysql.jdbc.Driver