spring:
    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: create
    datasource:
      url: jdbc:mysql://47.93.48.40:3306/mbcps?characterEncoding=UTF-8
      data-username: root
      data-password: password
      driver-class-name: com.mysql.jdbc.Driver