spring:
    jpa:
      hibernate:
        ddl-auto: create
    datasource:
      url: jdbc:mysql://aliyun.com:3306/mbcps
      data-username: root
      data-password: password
      driver-class-name: com.mysql.jdbc.Driver