spring:
    application:
        name: ace-monitor

server:
    port: 8764 #启动端口

eureka:
     instance:
        statusPageUrlPath: /actuator/info
        healthCheckUrlPath: /actuator/health
        prefer-ip-address: true

     client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
          defaultZone: http://${EUREKA_HOST:aliyun}:${EUREKA_PORT:8761}/eureka/

