version: '3'
services:
  user:
    image: registry.cn-hangzhou.aliyuncs.com/mengstar/mb-user
    deploy:
      replicas: 1
    networks:
      - springcloud-overlay
    ports:
      - "8401:8401"
    environment:
      - EUREKA_SERVER_ADDRESS=http://eureka2:8761/eureka/,http://eureka2:8761/eureka/,http://eureka3:8761/eureka/
      - CONFIG_HOST=config
      - CONFIG_POST=8788
  oa_php:
    image: registry.cn-hangzhou.aliyuncs.com/mengstar/mb-oa
    deploy:
      replicas: 1
    networks:
      - springcloud-overlay
    ports:
      - "8500:80"
networks:
  springcloud-overlay:
    external:
      name: springcloud-overlay